---
volumes:
  freezing-data:
    external: true

services:

  #### Stock containers

  datadog:
    restart: unless-stopped

  beanstalkd:
    restart: unless-stopped

  nginx:
    restart: unless-stopped

  nginx-letsencrypt:
    restart: unless-stopped

  nginx-docker-gen:
    restart: unless-stopped

  # Database used for local development
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    container_name: freezing-mysql
    ports:
      - "3306:3306"
    volumes:
      - freezing-data:/var/lib/mysql
    # Run mysqld with ideal UTF-8 character set defaults
    # Thanks Javier Arias & Stack Overflow https://stackoverflow.com/a/50529359
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']  # yamllint disable-line rule:line-length
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-freezing}
      MYSQL_HOST: ${MYSQL_HOST:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-please-change-me-as-this-is-a-default}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-terrible-root-password-which-should-be-changed}  # yamllint disable-line rule:line-length
      MYSQL_USER: ${MYSQL_USER:-freezing}

  #### Freezing Saddles containers

  freezing-sync:
    image: ${FREEZING_SYNC_IMAGE:-freezingsaddles/freezing-sync:latest}
    restart: unless-stopped
    environment:
      BEANSTALKD_HOST: ${BEANSTALKD_HOST:-beanstalkd}
      BEANSTALKD_PORT: ${BEANSTALKD_PORT:-11300}
      MYSQL_HOST: ${MYSQL_HOST:-mysql}
      MYSQL_PORT: ${MYSQL_HOST:-3306}
      SQLALCHEMY_SILENCE_UBER_WARNING: ${SQLALCHEMY_SILENCE_UBER_WARNING:-false}
      SQLALCHEMY_URL: ${SQLALCHEMY_URL}
      SQLALCHEMY_WARN_20: ${SQLALCHEMY_WARN_20:-true}
    depends_on:
      - beanstalkd
      - mysql

  freezing-nq:
    image: ${FREEZING_NQ_IMAGE:-freezingsaddles/freezing-nq:latest}
    restart: unless-stopped
    depends_on:
      - beanstalkd

  freezing-web:
    image: ${FREEZING_WEB_IMAGE:-freezingsaddles/freezing-web:latest}
    restart: unless-stopped
    depends_on:
      - beanstalkd
      - mysql
    ports:
      - 8000:8000
    environment:
      COMPETITION_TITLE: ${COMPETITION_TITLE}
      DEBUG: ${DEBUG}
      END_DATE: ${END_DATE}
      ENVIRONMENT: ${ENVIRONMENT}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${FREEZING_WEB_FQDN}
      MAIN_TEAM: ${MAIN_TEAM}
      OBSERVER_TEAMS: ${OBSERVER_TEAMS}
      SECRET_KEY: ${SECRET_KEY}
      SQLALCHEMY_SILENCE_UBER_WARNING: ${SQLALCHEMY_SILENCE_UBER_WARNING:-false}
      SQLALCHEMY_URL: ${SQLALCHEMY_URL}
      SQLALCHEMY_WARN_20: ${SQLALCHEMY_WARN_20:-1}
      START_DATE: ${START_DATE}
      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}
      TEAMS: ${TEAMS}
      TIMEZONE: ${TIMEZONE:-America/New_York}
      VIRTUAL_HOST: ${FREEZING_WEB_FQDN}
